---
- name: 1-0001-24_OSUser - modify user
  user:
    name: '{{ item.name }}'
    password: '{{ item.password | password_hash("sha512","salt") if "password" in item else "!!" }}'
    uid: '{{ item.uid | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    groups: '{{ item.sub_groups | default(omit) }}'
    home: '{{ item.home_dir | default(omit)}}'
    shell: '{{ item.shell | default(omit) }}'
    state: 'present'
  with_items: base_base.ID.user

